#!/bin/sh
#
#
# MOOTOMBO Nagios Plugin - check_mootombo_unowned_files
#
# Copyright 1997-2016 devXive - research and development. All rights reserved.
#
# http://www.devxive.com
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by devXive to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and devXive and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or devXive distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.
#
#
# Standard Nagios plugin return codes.
STATUS_OK=0
STATUS_WARNING=1
STATUS_CRITICAL=2
STATUS_UNKNOWN=3

# Vars
CUTOFF=40
STATUSDIR=/var/cache/nagios_status
STATUS=${STATUSDIR}/nouser

if [ ! -d ${STATUSDIR} ]; then
        mkdir -p ${STATUSDIR}
fi

tmp=`tempfile`
trap "rm -f '$tmp'" exit

if command -v ionice >/dev/null 2>&1; then
	prefix="ionice -c 3 -t"  # idle priority, ignore errors
fi

$prefix find / -fstype proc -prune -o -nouser | head -n "$CUTOFF" > "$tmp"

if [ -s "$tmp" ]; then
	echo "WARN"
	c="$(wc -l < "$tmp")"
	if [ "$c" -lt "$CUTOFF" ] ; then
		echo "Warn: $c unowned files on system."
		cat "$tmp"
	else
		echo "Warn: Lots of unowned files on system:"
		cat "$tmp"
		echo "..."
	fi
else
	echo "OK"
	echo "OK: No unowned files on system."
fi > "$STATUS"