#!/bin/sh
#
#    14-mcs-head - print head informations
#    Copyright (C) 2009-2016 devXive - research and development
#
#    Authors: Lahmizzar Valeryon
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
printf "\nMOOTOMBO Corporate Server 3.0:\n"
printf "================================\n\n"
printf "The MCS is prepaired for monitoring with Nagios through the UCS Master.\n\n"
printf "You can log into the Univention Management Console - the principal tool to manage\n"
printf "users, groups, etc. - using the "Administrator" account and the password selected\n"
printf "for the root user on the master domain controller.\n"
