#!/bin/sh
#
#    15-mcs-stats - print informations about disc space and uptime
#    Copyright (C) 2009-2016 devXive - research and development
#
#    Authors: Lahmizzar Valeryon
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Vars
MCS_UPTIMEP_RAW=$(uptime -p)
MCS_UPTIMEP=U${MCS_UPTIMEP_RAW:1}
MCS_UPTIMES=$(uptime -s)
MCS_DISCFREEMB=`stat -f --printf="%a * %s / 1024 / 1000\n" / | bc`
MCS_DISCFREEGB=`stat -f --printf="%a * %s / 1024 / 1000000\n" / | bc`

# Colors
BLACK=$(tput setaf 0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
LIME_YELLOW=$(tput setaf 190)
POWDER_BLUE=$(tput setaf 153)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)
BRIGHT=$(tput bold)
NORMAL=$(tput sgr0)
BLINK=$(tput blink)
REVERSE=$(tput smso)
UNDERLINE=$(tput smul)

# Stats
printf "\nMootombo Corporate Server Stats:\n"
printf "================================\n\n"
printf " Uptime:       ${MCS_UPTIMEP} (${YELLOW}${MCS_UPTIMES}${NORMAL})\n"
printf " Main HDD:     Free space ${GREEN}${MCS_DISCFREEGB}GB${NORMAL} (${MCS_DISCFREEMB}MB)\n"
