#!/bin/sh
#
#    15-mcs-stats - print informations about disc space and uptime
#    Copyright (C) 2009-2016 devXive - research and development
#
#    Authors: Lahmizzar Valeryon
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Stats
if [ -f /dev/sdb ]; then
	MCS_DISCFREEMBB=`stat -f --printf="%a * %s / 1024 / 1000\n" /media/ocdrive | bc`
	MCS_DISCFREEGBB=`stat -f --printf="%a * %s / 1024 / 1000000\n" /media/ocdrive | bc`
	printf " Second HDD:   Free space ${GREEN}${MCS_DISCFREEGBB}GB${NORMAL} (${MCS_DISCFREEMBB}MB)\n"
fi
